// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNetECommerceShop.Models;

#nullable disable

namespace MyNetECommerceShop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240926183523_initializeMigration")]
    partial class initializeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNetECommerceShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Clothing & Accessories"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Home & Furniture"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Collectibles & Antiques"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("MyNetECommerceShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            ListPrice = 89.0,
                            ProductName = "Wood Table"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            ListPrice = 99.0,
                            ProductName = "Lazy sofa"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            ListPrice = 29.0,
                            ProductName = "Used Wood Chair"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 9,
                            ListPrice = 15.0,
                            ProductName = "Lighter"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            ListPrice = 59.0,
                            ProductName = "Wood Shelf"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            ListPrice = 85.0,
                            ProductName = "Wood Table"
                        });
                });

            modelBuilder.Entity("MyNetECommerceShop.Models.Product", b =>
                {
                    b.HasOne("MyNetECommerceShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
